# fly.toml app configuration file generated for wasserdatenaufbereitung-lk-vg on 2025-06-18T11:15:58+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wasserdatenaufbereitung-lk-vg'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "comments_data"
  destination = "/app/data"

[deploy]
  release_command = "node database.js"